### ISSUE TITLE
Support session timer

### ISSUE THREAD

**Issue by portsip** [onsip/SIP.js#913] opened 2021-03-03 09:46 UTC
**Is your feature request related to a problem? Please describe.**
Since the server uses the session timer to handle the session timeout but seems SIP.JS doesn't support this will cause the call not to hang up after the user uses F5 to refresh the web page.

**Describe the solution you'd like**
Implement the RFC 4028.

**Describe alternatives you've considered**

**Additional context**

**Comment by james-criscuolo** [comment] 2021-03-03 14:12
Closing as duplicate of #18. Also note, we have a branch where we believe this was working: https://github.com/onsip/SIP.js/tree/session-timers

The branch has not been updated for the new API, but was built in a way that it may port fairly cleanly, if you have the time to put a PR together.

**Closed by james-criscuolo** 2021-03-03 14:12 UTC
