### ISSUE TITLE
Add dist folder to node module package 

### ISSUE THREAD

**Issue by VadimDez** [onsip/SIP.js#405] opened 2017-04-25 09:32 UTC
Add `dist` folder with production-ready minified file(s) to node package.

**Comment by egreenmachine** [comment] 2017-04-25 13:02
Duplicate of #390. We are looking to do this for a future release.

**Closed by egreenmachine** 2017-04-25 13:02 UTC
Labels: duplicate

**Comment by VadimDez** [comment] 2017-04-25 13:03
Thanks, didn't find it.
