### ISSUE TITLE
setRemoteDescription failed. OperationError Failed to execute 'setRemoteDescription' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by SD-Gaming** [onsip/SIP.js#821] opened 2020-06-09 06:55 UTC
**Describe the bug**
I use desktop chrome video call my mobile-phone which use chrome for android, they are the same website same code run here, 
When my phone accepts the call, there is an error come out, and the session is stoped.

**Logs**
...... 
 register success
......
13:58:01.385 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:01 GMT+0800 (中国标准时间) | sip.Transport | Received WebSocket binary message:

INVITE sip:4u76c6an@kd4oeafiendd.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.16.232.164:10443;branch=z9hG4bK-524287-1---596d1c24be32945f;rport
Max-Forwards: 17
Contact: <sip:102@172.16.232.164:10443;transport=wss>
To: <sip:101@sip.webrtc.site>
From: <sip:102@sip.webrtc.site>;tag=7215785f
Call-ID: BTVxcCKhIM2j98J9NJyq4g..
CSeq: 1 INVITE
Accept-Language: en
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, SUBSCRIBE, UPDATE, INFO, MESSAGE
Content-Type: application/sdp
Supported: outbound, path, replaces, norefersub, tdialog
User-Agent: PortSIP WebRTCGateway 12.2.0
X-Session-Id: 6675606956595478685
Content-Length: 4319

v=0
o=- 8390526214998386799 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS stream_label
a=ice-lite
m=audio 34776 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 112.124.45.142
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2094898416 1 udp 2122260223 112.124.45.142 34776 typ host generation 0 network-id 1
a=candidate:845045760 1 tcp 1518280447 112.124.45.142 34776 typ host tcptype passive generation 0 network-id 1
a=ice-ufrag:M0rP
a=ice-pwd:iEOkq53FhrbJMmRHaRH+sd1L
a=ice-options:trickle
a=fingerprint:sha-256 0C:0A:18:71:A3:A2:26:2F:9F:CD:A6:CE:C4:F6:54:F3:87:C8:4E:25:B7:3D:22:09:3E:D4:87:AD:46:BD:90:04
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1312452337 cname:7bfgWRxpMKVu/4yi
a=ssrc:1312452337 msid:stream_label audio_label
a=ssrc:1312452337 mslabel:stream_label
a=ssrc:1312452337 label:audio_label
a=sendrecv
m=video 34777 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 112.124.45.142
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2094898416 1 udp 2122260223 112.124.45.142 34777 typ host generation 0 network-id 1
a=candidate:845045760 1 tcp 1518280447 112.124.45.142 34777 typ host tcptype passive generation 0 network-id 1
a=ice-ufrag:M0rP
a=ice-pwd:iEOkq53FhrbJMmRHaRH+sd1L
a=ice-options:trickle
a=fingerprint:sha-256 0C:0A:18:71:A3:A2:26:2F:9F:CD:A6:CE:C4:F6:54:F3:87:C8:4E:25:B7:3D:22:09:3E:D4:87:AD:46:BD:90:04
a=setup:actpass
a=mid:video
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:7 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 SESSION_ID=44129;level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 SESSION_ID=44129;level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 SESSION_ID=44129;level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 SESSION_ID=44129;level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 3525308539 2362321295
a=ssrc:3525308539 cname:7bfgWRxpMKVu/4yi
a=ssrc:3525308539 msid:stream_label video_label
a=ssrc:3525308539 mslabel:stream_label
a=ssrc:3525308539 label:video_label
a=ssrc:2362321295 cname:7bfgWRxpMKVu/4yi
a=ssrc:2362321295 msid:stream_label video_label
a=ssrc:2362321295 mslabel:stream_label
a=ssrc:2362321295 label:video_label
a=sendrecv

13:58:01.456 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:01 GMT+0800 (中国标准时间) | sip.Transport | Sending WebSocket message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 172.16.232.164:10443;branch=z9hG4bK-524287-1---596d1c24be32945f;rport
From: <sip:102@sip.webrtc.site>;tag=7215785f
To: <sip:101@sip.webrtc.site>
CSeq: 1 INVITE
Call-ID: BTVxcCKhIM2j98J9NJyq4g..
Supported: outbound
User-Agent: SIP.js/0.16.1
Content-Length: 0

13:58:01.458 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:01 GMT+0800 (中国标准时间) | sip.Invitation | Invitation.progress
13:58:01.460 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:01 GMT+0800 (中国标准时间) | sip.invite-dialog | INVITE dialog BTVxcCKhIM2j98J9NJyq4g..phnqfn19be7215785f constructed
13:58:01.461 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:01 GMT+0800 (中国标准时间) | sip.Transport | Sending WebSocket message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 172.16.232.164:10443;branch=z9hG4bK-524287-1---596d1c24be32945f;rport
From: <sip:102@sip.webrtc.site>;tag=7215785f
To: <sip:101@sip.webrtc.site>;tag=phnqfn19be
CSeq: 1 INVITE
Call-ID: BTVxcCKhIM2j98J9NJyq4g..
Supported: outbound
User-Agent: SIP.js/0.16.1
Contact: <sip:4u76c6an@kd4oeafiendd.invalid;transport=ws>
Content-Length: 0

13:58:01.463 warpper.ts?36cf:65 receive invite, state is: Initial
13:58:06.971 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:06 GMT+0800 (中国标准时间) | sip.Invitation | Invitation.accept
13:58:06.974 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:06 GMT+0800 (中国标准时间) | sip.Invitation | Session BTVxcCKhIM2j98J9NJyq4g..7215785f transitioned to state Establishing
13:58:06.975 warpper.ts?36cf:89 incoming call status change: Establishing
13:58:06.978 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:06 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | SessionDescriptionHandlerOptions: {}
13:58:06.979 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:06 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | initPeerConnection
13:58:06.985 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:06 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | New peer connection created
13:58:07.050 logger-factory.js?50e5:85 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | setRemoteDescription failed. OperationError Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
13:58:07.051 logger-factory.js?50e5:85 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Invitation | setRemoteDescription failed. OperationError Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
13:58:07.052 logger-factory.js?50e5:85 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Invitation | setRemoteDescription failed. OperationError Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
13:58:07.052 logger-factory.js?50e5:85 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Invitation | A session description handler occurred while sending response
13:58:07.053 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Transport | Sending WebSocket message:

SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/WSS 172.16.232.164:10443;branch=z9hG4bK-524287-1---596d1c24be32945f;rport
From: <sip:102@sip.webrtc.site>;tag=7215785f
To: <sip:101@sip.webrtc.site>;tag=phnqfn19be
CSeq: 1 INVITE
Call-ID: BTVxcCKhIM2j98J9NJyq4g..
Supported: outbound
User-Agent: SIP.js/0.16.1
Content-Length: 0

13:58:07.054 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Invitation | Session BTVxcCKhIM2j98J9NJyq4g..7215785f transitioned to state Terminated
13:58:07.054 warpper.ts?36cf:89 incoming call status change: Terminated
13:58:07.060 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Invitation | Session BTVxcCKhIM2j98J9NJyq4g..7215785f in state Terminated is being disposed
13:58:07.060 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | closing PeerConnection
13:58:07.060 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.SessionDescriptionHandler | resetIceGatheringComplete
13:58:07.097 session-description-handler.js?12b1:227 Uncaught (in promise) Error: setRemoteDescription failed. OperationError Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
13:58:07.125 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.Transport | Received WebSocket binary message:

ACK sip:4u76c6an@kd4oeafiendd.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.16.232.164:10443;branch=z9hG4bK-524287-1---596d1c24be32945f;rport
Max-Forwards: 70
To: <sip:101@sip.webrtc.site>;tag=phnqfn19be
From: <sip:102@sip.webrtc.site>;tag=7215785f
Call-ID: BTVxcCKhIM2j98J9NJyq4g..
CSeq: 1 ACK
Content-Length: 0

13:58:07.142 logger-factory.js?50e5:93 Tue Jun 09 2020 13:58:07 GMT+0800 (中国标准时间) | sip.invite-dialog | INVITE dialog BTVxcCKhIM2j98J9NJyq4g..phnqfn19be7215785f destroyed

**To Reproduce (if possible)**
1. register both sides;
2. call video call from desktop Chrome to mobile-phone Chrome;
3. answer the call in the phone;

**Expected behavior**
A session is connected, the video is loaded

**Observed behavior**
A session fail, no video.

**Environment Information**
 - Window 10 Chrome  83.0.4103.97 （64 bit）
 - Android 10 Chrome 83.0.4103.96
- SIP.js 0.16.1

**Additional context**
the audio call is normal, desktop video call iPhone is also normal, and the desktop to desktop is normal too.

**Comment by egreenmachine** [comment] 2020-06-18 15:24
Hi. In my experience the issue is almost always related to the H264 video attributes. `a=fmtp:96 SESSION_ID=44129;level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f` spectically the `profile-level-id`. The best way to try and debug this is to use modifiers to remove the different video tracks until it starts working. 

This level of media control is really outside of the realm of SIP.js. I am going to close this issue, if you have any follow up please post on our [Google Group](https://groups.google.com/forum/#!forum/sip_js)

**Closed by egreenmachine** 2020-06-18 15:24 UTC
