### ISSUE TITLE
sip.transport not trying to reconnect after fresswitch restart

### ISSUE THREAD

**Issue by anshkatriya** [onsip/SIP.js#491] opened 2017-12-12 06:07 UTC
Hello,
After restarting FreeSWITCH, SIP.js trying to reconnect for WebSocket connection for server. It's trying re-connection for every 2-3 seconds until it doesn't get connected to server through wss.

Currently it's connected but not registered with system. When SIP.js sending REGISTER request to server,

```
REGISTER sip:xxxxxx SIP/2.0
Via: SIP/2.0/WSS 4n07b9ilqs0d.invalid;branch=z9hG4bK844400
Max-Forwards: 70
To: "109" <sip:xxxxxx@xxxxxx>
From: "109" <sip:xxxxxx@xxxxxx>;tag=01p0ijah5n
Call-ID: m817a2po9ecp9qek8tejc6
CSeq: 84 REGISTER
Authorization: Digest algorithm=MD5, username="xxxxxx", realm="xxxxxx", nonce="33d56bcc-c92b-4ea1-90c3-1ff279edac84", uri="sip:xxxxxx", response="331547f4059a2a52e76fcf13b68fda7a", qop=auth, cnonce="ep2nv7ocp0vi", nc=00000001
Contact: <sip:hm4evra8@4n07b9ilqs0d.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:dfb14c64-d777-445f-8c45-d73d9e17d064>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, 100rel, outbound
User-Agent: SIP.js
Content-Length: 0
```

After REGISTER server, FreeSWITCH responding 503 Maxicum Calls  In Progress. I don't know why it's sending 503,

```
SIP/2.0 503 Maximum Calls In Progress
Via: SIP/2.0/WSS 4n07b9ilqs0d.invalid;branch=z9hG4bK844400;received=x.x.x.;rport=38710
From: "109" <sip:xxxxxx@xxxxxx>;tag=01p0ijah5n
To: "109" <sip:xxxxxx@xxxxxx>;tag=BXrrpZ9gjcHae
Call-ID: m817a2po9ecp9qek8tejc6
CSeq: 84 REGISTER
Retry-After: 300
User-Agent: FreeSWITCH-mod_sofia/1.6.19~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: path, replaces
Content-Length: 0
```

After receiving 503 from serve, SIP.js not trying to send any other REGISTER request after 3600 seconds. Ideally, It should send re-register request to server if it's not registered with server.

Can anyone help me with this?

**Comment by egreenmachine** [comment] 2017-12-12 15:10
This is a duplicate of #472. Closing in favor of that issue.

**Closed by egreenmachine** 2017-12-12 15:10 UTC
Labels: bug, duplicate
