### ISSUE TITLE
Session status not refreshed after ReInvite

### ISSUE THREAD

**Issue by Demitrius** [onsip/SIP.js#183] opened 2015-06-04 09:35 UTC
Hello,

The session status is STATUS_TERMINATED when second call established and active

Reproduce:
- Make first call and terminate
- Make second call (Invite button close to DTMF text)
- While second call established, try to send dtmf info

JS Console:
Uncaught INVALID_STATE_ERROR: Invalid status: 9 (STATUS_TERMINATED)
     module.exports.Session.dtmf @ sip-0.7.0.js:4720

**Comment by joseph-onsip** [comment] 2015-06-05 17:40
Can you post a link to the code you're running? Here's a [JSFiddle](http://jsfiddle.net/r2fmd4Lt/) demonstrating that the call scenario you've described works correctly, so the problem is probably in the application code rather than in sip.js.

**Comment by Demitrius** [comment] 2015-06-08 07:12
Hello,

First, accept SSL for WebSocket  https://rock.dwide.com:7443

Open demo page  https://jmitty.cc/sipjsdemo/

Click Create UA button

Type URI in text box number 74957777771 (autoanswer) and click INVITE

New block will show at right

After accept - try send dtmf digit - must looks good.

Then click BYE

Then click Invite (in same block)

After accept - send dtmf digit again - must looks as at attached screen.





Пятница,  5 июня 2015, 10:40 -07:00 от Joseph Frazier <notifications@github.com>:
>Can you post a link to the code you're running? Here's a  JSFiddle demonstrating that the call scenario you've described works correctly, so the problem is probably in the application code rather than in sip.js.
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Дмитрий Мордовин

**Comment by Demitrius** [comment] 2015-06-08 07:19
Screen

![screen](https://cloud.githubusercontent.com/assets/2479194/8029609/cdb78c96-0dc7-11e5-81a9-5651a209bc38.jpg)

**Comment by wakamoleguy** [comment] 2015-10-16 19:11
Hey @Demitrius.  I'm going through a lot of these issues, trying to get them up to date.  This looks like a bug in our demo phone, rather than a SIP.js issue itself.  I'll be honest that we have no intention of fixing it, since we really only use that for rudimentary purposes and don't have the resources to devote to it right now.

I'm going to close this ticket.  If you want to follow up with it, the source code for the demo phone is actually tracked in our [sipjs.com repo](https://github.com/onsip/sipjs.com) with our other website content.  You can submit a pull request there, if you find a solution.

**Closed by wakamoleguy** 2015-10-16 19:12 UTC

**Comment by jettying** [comment] 2017-12-29 09:24
@Demitrius how to make blind transfers? when i use this method [session.refer(target), https://sipjs.com/guides/transfer/], it throws INVALID_STATE_ERROR.
