### ISSUE TITLE
master branch ends session on transport error

### ISSUE THREAD

**Issue by jamesaylett** [onsip/SIP.js#167] opened 2015-04-09 14:29 UTC
Hi,

I've noticed that on the master branch, a session is terminated when a transport error occurs. Is this expected behavior? See below for a log trace:

> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket disconnected (code: 1006)
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket abrupt disconnection
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.ua | connection state set to 1
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.inviteclientcontext | closing INVITE session s68bl0buvd1ef7mkdr8lnglt8sbnor
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.invitecontext.mediahandler | s68bl0buvd1ef7mkdr8lnglt8sbnor | closing PeerConnection
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.dialog | s68bl0buvd1ef7mkdr8lq8dn74pf1ka500b618 | dialog s68bl0buvd1ef7mkdr8lq8dn74pf1ka500b618 deleted
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.inviteclientcontext | emitting event terminated
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.registercontext | emitting event unregistered
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.ua | emitting event unregistered
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.transport | trying to reconnect to WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test (reconnection attempt 1)
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:44 GMT+0100 (GMT Daylight Time) | sip.invitecontext.mediahandler | s68bl0buvd1ef7mkdr8lnglt8sbnor | emitting event iceConnectionClosed
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:48 GMT+0100 (GMT Daylight Time) | sip.transport | connecting to WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:48 GMT+0100 (GMT Daylight Time) | sip.ua | emitting event connecting
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:48 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test connected
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:48 GMT+0100 (GMT Daylight Time) | sip.ua | connection state set to 0
> sip-0.6.4.master.js:2681 Thu Apr 09 2015 15:10:48 GMT+0100 (GMT Daylight Time) | sip.ua | emitting event connected

In the release branch, you emit a session failed event but do not terminate the call. This allows me to reestablish the connection while the media is uninterrupted and clear the call with a bye once the transport is back, which I would assume is what is intended from reading http://sipjs.com/api/0.6.0/session/#failed. See below for a log trace from the release branch:

> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket disconnected (code: 1006)
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket abrupt disconnection
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.ua | connection state set to 1
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.inviteclientcontext | emitting event failed
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.registercontext | emitting event unregistered
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.ua | emitting event unregistered
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:13 GMT+0100 (GMT Daylight Time) | sip.transport | trying to reconnect to WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test (reconnection attempt 1)
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:17 GMT+0100 (GMT Daylight Time) | sip.transport | connecting to WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:17 GMT+0100 (GMT Daylight Time) | sip.ua | emitting event connecting
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:17 GMT+0100 (GMT Daylight Time) | sip.transport | WebSocket wss://WebRTCSIPGateway.jamesaylett.com/test connected
> sip-0.6.4.release.js:2680 Thu Apr 09 2015 15:03:17 GMT+0100 (GMT Daylight Time) | sip.ua | connection state set to 0

**Comment by wakamoleguy** [comment] 2015-04-21 16:04
The behavior of the `failed` event has been changed since the 0.6.4 release to better match the documentation.  That is, it is fired only when the *request* fails.  That is part of the difference you are seeing here.

That being said, we should leave the session going if at all possible.  We will need to patch master to not emit any event on the session in that case (It will still emit on the UA).  Behavior should already be defined for when an in-dialog request fails, so that shouldn't be an issue.

**Comment by james-onsip** [comment] 2015-04-21 21:17
I was able to replicate this problem, and pushed a fix on master. The event emissions are now more in line with what was intended. There were a few generic tests that I had to leave out (I'll get to them tomorrow), but I didn't want those to stop you from giving the fix a shot.

Let me know if the fix works for you.

**Comment by jamesaylett** [comment] 2015-04-22 15:00
I've tested with the fix and can confirm that the session is no longer terminated so this issue can be closed.

I would say with the changes to the failed event, I don't see any events fired if a session is connected and the transport fails. Is the ua.disconnected event fired when the transport fails? Reading the documentation, I assume that the ua.disconnected event is fired when a connection attempt fails but not when a connection itself fails.

**Comment by wakamoleguy** [comment] 2015-04-22 15:32
The `disconnected` (and likely `unregistered`) events should fire on the UA when the transport disconnects.

The documentation should be valid for any tagged 0.6.x version, as there shouldn't be any API-breaking changes between those versions.  That said, we've come a long way from 0.6.4, the event changes are behaving differently (although we believe more consistently), and the next version will be 0.7.0.  We're going to revise the documentation for that version to better describe the current state of events and such.

**Comment by james-onsip** [comment] 2015-04-22 16:38
The documentation is correct in that the 'disconnected' event means you are not connected, and you won't be trying to connect again. As long as you are actively trying to reconnect, no events are emitted, but if reconnection fails or succeeds (eventually), then you will be notified with an emission. That middle area may be needing an event.

In a similar way, the "isConnected" function on the UA is actually "Are you connected or actively trying to reconnect." A tweak to this wording may be helpful for 0.7.0, but I am pushing another commit to clarify the comment on that (and fix the reconnect logic), I'll update the documentation if necessary as well.

**Closed by james-onsip** 2015-04-22 16:38 UTC
Labels: bug
