### ISSUE TITLE
a lot ice candidates in google chrome

### ISSUE THREAD

**Issue by schirrmie** [onsip/SIP.js#485] opened 2017-11-21 20:03 UTC
Hi,
sorry for the next issue from me :)
I have the problem that I have no video in chrome. In firefox all works now.
In chrome I see the strange behaviour that I get a lot of ice candidates and ran into the ice checking timeout.
This is the example output:
```
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3013905414 1 udp 2122255103 2001::9d38:90d7:4f5:347c:e0ec:7d39 56236 typ host generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2649622271 1 udp 2122199807 fd18:1e23:678f::c965:e309:c6e0:2908 56237 typ host generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2679724667 1 udp 2122134271 fd18:1e23:678f::10 56238 typ host generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2013503289 1 udp 2122068735 fd18:1e23:678f::b913:3ca:d8e4:294 56239 typ host generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:917340262 1 udp 2121998079 192.168.6.10 56240 typ host generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:259744544 1 udp 2121932543 192.168.109.1 56241 typ host generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4242042849 1 udp 2121867007 192.168.153.1 56242 typ host generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3013905414 2 udp 2122255102 2001::9d38:90d7:4f5:347c:e0ec:7d39 56243 typ host generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2649622271 2 udp 2122199806 fd18:1e23:678f::c965:e309:c6e0:2908 56244 typ host generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2679724667 2 udp 2122134270 fd18:1e23:678f::10 56245 typ host generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2013503289 2 udp 2122068734 fd18:1e23:678f::b913:3ca:d8e4:294 56246 typ host generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:917340262 2 udp 2121998078 192.168.6.10 56247 typ host generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:259744544 2 udp 2121932542 192.168.109.1 56248 typ host generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4242042849 2 udp 2121867006 192.168.153.1 56249 typ host generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3013905414 1 udp 2122255103 2001::9d38:90d7:4f5:347c:e0ec:7d39 56250 typ host generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2649622271 1 udp 2122199807 fd18:1e23:678f::c965:e309:c6e0:2908 56251 typ host generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2679724667 1 udp 2122134271 fd18:1e23:678f::10 56252 typ host generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2013503289 1 udp 2122068735 fd18:1e23:678f::b913:3ca:d8e4:294 56253 typ host generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:917340262 1 udp 2121998079 192.168.6.10 56254 typ host generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:259744544 1 udp 2121932543 192.168.109.1 56255 typ host generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4242042849 1 udp 2121867007 192.168.153.1 56256 typ host generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3013905414 2 udp 2122255102 2001::9d38:90d7:4f5:347c:e0ec:7d39 56257 typ host generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2649622271 2 udp 2122199806 fd18:1e23:678f::c965:e309:c6e0:2908 56258 typ host generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2679724667 2 udp 2122134270 fd18:1e23:678f::10 56259 typ host generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2013503289 2 udp 2122068734 fd18:1e23:678f::b913:3ca:d8e4:294 56260 typ host generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:917340262 2 udp 2121998078 192.168.6.10 56261 typ host generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:259744544 2 udp 2121932542 192.168.109.1 56262 typ host generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4242042849 2 udp 2121867006 192.168.153.1 56263 typ host generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4247220470 1 tcp 1518275327 2001::9d38:90d7:4f5:347c:e0ec:7d39 9 typ host tcptype active generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3547200015 1 tcp 1518220031 fd18:1e23:678f::c965:e309:c6e0:2908 9 typ host tcptype active generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3510281867 1 tcp 1518154495 fd18:1e23:678f::10 9 typ host tcptype active generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:914383817 1 tcp 1518088959 fd18:1e23:678f::b913:3ca:d8e4:294 9 typ host tcptype active generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2016312470 1 tcp 1518018303 192.168.6.10 9 typ host tcptype active generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1106812880 1 tcp 1517952767 192.168.109.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2992345873 1 tcp 1517887231 192.168.153.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4247220470 2 tcp 1518275326 2001::9d38:90d7:4f5:347c:e0ec:7d39 9 typ host tcptype active generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3547200015 2 tcp 1518220030 fd18:1e23:678f::c965:e309:c6e0:2908 9 typ host tcptype active generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3510281867 2 tcp 1518154494 fd18:1e23:678f::10 9 typ host tcptype active generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:914383817 2 tcp 1518088958 fd18:1e23:678f::b913:3ca:d8e4:294 9 typ host tcptype active generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2016312470 2 tcp 1518018302 192.168.6.10 9 typ host tcptype active generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1106812880 2 tcp 1517952766 192.168.109.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2992345873 2 tcp 1517887230 192.168.153.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4247220470 1 tcp 1518275327 2001::9d38:90d7:4f5:347c:e0ec:7d39 9 typ host tcptype active generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3547200015 1 tcp 1518220031 fd18:1e23:678f::c965:e309:c6e0:2908 9 typ host tcptype active generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3510281867 1 tcp 1518154495 fd18:1e23:678f::10 9 typ host tcptype active generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:914383817 1 tcp 1518088959 fd18:1e23:678f::b913:3ca:d8e4:294 9 typ host tcptype active generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2016312470 1 tcp 1518018303 192.168.6.10 9 typ host tcptype active generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1106812880 1 tcp 1517952767 192.168.109.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2992345873 1 tcp 1517887231 192.168.153.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:4247220470 2 tcp 1518275326 2001::9d38:90d7:4f5:347c:e0ec:7d39 9 typ host tcptype active generation 0 ufrag LTVy network-id 1 network-cost 50
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3547200015 2 tcp 1518220030 fd18:1e23:678f::c965:e309:c6e0:2908 9 typ host tcptype active generation 0 ufrag LTVy network-id 3
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:3510281867 2 tcp 1518154494 fd18:1e23:678f::10 9 typ host tcptype active generation 0 ufrag LTVy network-id 4
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:914383817 2 tcp 1518088958 fd18:1e23:678f::b913:3ca:d8e4:294 9 typ host tcptype active generation 0 ufrag LTVy network-id 5
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2016312470 2 tcp 1518018302 192.168.6.10 9 typ host tcptype active generation 0 ufrag LTVy network-id 2
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:1106812880 2 tcp 1517952766 192.168.109.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 6
sip.min.js:38 Tue Nov 21 2017 20:53:09 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2992345873 2 tcp 1517887230 192.168.153.1 9 typ host tcptype active generation 0 ufrag LTVy network-id 7
sip.min.js:38 Tue Nov 21 2017 20:53:14 GMT+0100 (Mitteleuropäische Zeit) | sip.invitecontext.sessionDescriptionHandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
sip.min.js:38 Tue Nov 21 2017 20:53:14 GMT+0100 (Mitteleuropäische Zeit) | sip.dialog | new UAC dialog created with status CONFIRMED
```
I do not have IPV6 and some IPs are correct but some are not from me!

At this ice site https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
I only get 4 ice candidates.

I also detect, if I set a wrong url in iceServers I get the same candidates. This is my example code:
```
        var configuration = {
          ...
          sessionDescriptionHandlerFactoryOptions: {
            peerConnectionOptions: {
              rtcConfiguration: {
                rtcpMuxPolicy: 'negotiate',
                iceTransportPolicy: 'all',
                iceServers: [{urls: 'stun:suffball.ath.cx:3478'}]
              }
            }
          }
        };

```
I use the latest SIP.js Version 0.8.4

Is there anything wrong?

Regards
schirrmie

**Comment by egreenmachine** [comment] 2017-11-21 20:44
I just tested using the `iceServer` that you provided and I cannot reproduce. All is working correctly for me.

**Comment by egreenmachine** [comment] 2017-11-21 20:48
Are you doing any sort of re-invites? Also, this is most likely expected behavior if you have a lot of virtual interfaces or VPN connections.

**Comment by schirrmie** [comment] 2017-11-22 07:17
Hmm maybe it is not a problem with ice candidates. If I set video to false, audio works fine. But If I set video to true than I have no video and no audio. I use asterisk 15.1 and firefox works fine but chrome does not want. I don't see any error in sdp and no I don't do any re-invites.
I will look into it ...

Thank You for help!

**Comment by egreenmachine** [comment] 2017-11-22 14:31
I am going to close this issue. If you track it down to an issue in SIP.js feel free to re-open this or create a new issue. For questions, the best place to ask is on our [mailing list](https://groups.google.com/forum/#!forum/sip_js)

**Closed by egreenmachine** 2017-11-22 14:31 UTC
Labels: question, Session Description Handler
