### ISSUE TITLE
Hold not working on Firefox

### ISSUE THREAD

**Issue by m-heinemann** [onsip/SIP.js#840] opened 2020-07-22 17:03 UTC
**Describe the bug**
I am trying to migrate to version 0.17.0

When I try to place the call on "hold" in Firefox, although neither party can hear the other, the second party does not hear any hold music and the status of the call is not set to hold.
After some investigation this is what I have found to be the issue:
It seems like the sdp is modified AFTER the hold modifier, and the "a=sendrecv" is added back into the sdp (in addition to the "a=sendonly" which is already there)

**Logs**
https://gist.github.com/m-heinemann/b32ff6af8c281e4349b6b2720c3a8dc3

**Steps to Reproduce**
1. Clone the SIP.js repo
2. Run `npm install` and `npm run build-demo`
3. Go to file:///{localPath}/SIP.js/demo/demo-1.html on a Firefox browser
4. Click Connect and Place Call. Open the dev tools and clear the console.
5. Check the "Hold" checkbox.  Now observe the sdp that is printed in the console.  You will see that "a=sendrecv" appears in the sdp that is sent from the server to the client, in addition to "a=sendonly" which appears further down.

**Expected behavior**
Placing the call on "hold" should play music for the second party and should set the call status to on hold

**Observed behavior**
Neither party could hear audio from the other party, BUT the second party did not hear music and the call status was not set to hold

**Environment Information**
 - Node.js
 - Firefox version 78.0.2

**Comment by john-e-riordan** [comment] 2020-07-22 21:05
I've reproduced this issue using the demo in 0.17.1 . Working on fixing it. Thanks.

**Comment by m-heinemann** [comment] 2020-07-23 16:22
Great, thanks so much for your quick response.  Please keep me posted about any updates.

**Comment by m-heinemann** [comment] 2020-07-28 14:52
Has there been any progress yet?

**Comment by SD-Gaming** [comment] 2020-07-29 03:54
why can't I update the 0.17.1 version in npm?
the latest is 0.17.0.

**Comment by james-criscuolo** [comment] 2020-07-29 15:58
https://www.npmjs.com/package/sip.js

0.17.1 is available via NPM, and has been for 16 days.

**Comment by SD-Gaming** [comment] 2020-07-30 03:23
thanks for your working, @james-criscuolo 
I see the npmjs.com,
but when I install the 0.17.1, strangely it fails. 

![20200730112216](https://user-images.githubusercontent.com/25575589/88876942-f3f28880-d256-11ea-88f2-3e7eafee2f4b.png)

**Comment by james-criscuolo** [comment] 2020-07-30 11:31
`npm info sip.js` should tell you where you are trying to pull from and why it isn't grabbing the latest. Please go to our google group with further questions, as this issue is for a different topic.

**Comment by egreenmachine** [comment] 2020-07-30 12:00
@m-heinemann - The way that hold is currently working is legal per the SDP standard. What is happening is that we are changing the track level attribute to `sendonly` but the session level attribute is remaining `sendrecv`. We are going to adjust the modifier so that both all attributes are set accordingly when a call is placed on hold/unhold. We hope to have this fixed soon.

**Comment by m-heinemann** [comment] 2020-07-31 14:09
@egreenmachine Thank you for the update

**Comment by m-heinemann** [comment] 2020-08-12 17:06
@egreenmachine Is there an approximate ETA for this?

**Comment by john-e-riordan** [comment] 2020-08-13 15:30
I do not think this is a bug having to do with the SDP...

The first "a=sendrecv" appears at the session-level of the SDP and the second "a=sendonly" is at the media-level.

From https://tools.ietf.org/html/rfc4566#section-5.13...

>    Attributes are the primary means for extending SDP.  Attributes may
>    be defined to be used as "session-level" attributes, "media-level"
>    attributes, or both.
> 
>    A media description may have any number of attributes ("a=" fields)
>    that are media specific.  These are referred to as "media-level"
>    attributes and add information about the media stream.  Attribute
>    fields can also be added before the first media field; these
>    "session-level" attributes convey additional information that applies
>    to the conference as a whole rather than to individual media.

From https://lists.cs.columbia.edu/pipermail/sip-implementors/2015-May/030141.html...

> > Hi Team,
> >
> > I've a small doubt. I have a working call where A party is talking to B party. B party putts the call on hold, however I see "Session Attribute" with a value "SendOnly". Mostly I've seen it coming in Media Attribute.
> >
> > "Session Attribute (a): sendonly" Instead of "Media Attribute (a): SendOnly".
> >
> > What's the difference?
> 
> When used at session level this attribute serves as a default for each 
> media section. So this means sendonly for *all* the media in the call, 
> except for media sections that explicitly override it.
> 
> In the case where there is only one media section (audio) it means 
> exactly the same thing if it only appears at session level as it does if 
> it only appears at media level.

So the SDP being generated by Firefox is correct and should not cause any issues.

**Comment by john-e-riordan** [comment] 2020-08-13 15:32
I'm now looking at `SimpleUser` to check if there is an issue with the way the hold modifier is being applied that might cause hold to music not to be sent by a user agent who placed the call on hold (a user agent capable of sending moh) or to not be received by the remote end.

**Comment by john-e-riordan** [comment] 2020-08-13 15:49
There is an issue with hold in `SimpleUser`. The hold modifier is being incorrectly to the SDP answer from the peer resulting in the received SDP ...
```
v=0
o=F 1597303635 1597303637 IN IP4 199.7.173.157
s=F
c=IN IP4 199.7.173.74
t=0 0
m=audio 55758 UDP/TLS/RTP/SAVPF 9 101
a=silenceSupp:off - - - -
a=mid:0
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=recvonly
a=rtcp:55758
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 6D:02:EE:40:96:11:22:FE:3A:55:76:83:A2:AA:1F:65:4E:CF:A0:01
a=ptime:20
a=ice-ufrag:tcg2UzcY
a=ice-pwd:fIwn1GZVikaagVfYTqYVOP00h7
a=candidate:6JCbJYuYWwaC2UnX 1 UDP 2130706431 199.7.173.74 55758 typ host
```
... being converted to ...
```
v=0
o=F 1597303635 1597303637 IN IP4 199.7.173.157
s=F
c=IN IP4 199.7.173.74
t=0 0
m=audio 55758 UDP/TLS/RTP/SAVPF 9 101
a=silenceSupp:off - - - -
a=mid:0
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=inactive
a=rtcp:55758
a=rtcp-mux
a=setup:active
a=fingerprint:sha-1 6D:02:EE:40:96:11:22:FE:3A:55:76:83:A2:AA:1F:65:4E:CF:A0:01
a=ptime:20
a=ice-ufrag:tcg2UzcY
a=ice-pwd:fIwn1GZVikaagVfYTqYVOP00h7
a=candidate:6JCbJYuYWwaC2UnX 1 UDP 2130706431 199.7.173.74 55758 typ host
```

The a=inactive would cause the user agent which initiated the hold to not send music on hold (or any other media).

Putting a pull request together to fix this.

**Comment by john-e-riordan** [comment] 2020-08-13 16:57
@m-heinemann Can you please retest your use case using pull request #844 - thanks.

**Comment by m-heinemann** [comment] 2020-08-13 17:54
@john-e-riordan Thank you so much for your response. I will retest using pull request #844 and let you know what happens.

**Comment by m-heinemann** [comment] 2020-08-14 13:28
@john-e-riordan Unfortunately the pull request did not solve my issue.

**Comment by john-e-riordan** [comment] 2020-08-14 14:09
@m-heinemann

Are you using `SimpleUser`?

In your original gist you show the SDP answer from Freeswitch after the modifier has been applied on like 320: (https://gist.github.com/m-heinemann/b32ff6af8c281e4349b6b2720c3a8dc3#file-sip-js-console-txt-L320)

On line 344 (https://gist.github.com/m-heinemann/b32ff6af8c281e4349b6b2720c3a8dc3#file-sip-js-console-txt-L344), I see `a=inactive` which I believe would cause the problem your are reporting. It should be `a=recvonly`. Is it still showing up as `a=inactive`?

The pull request should fix this for `SimpleUser`. I will double check that it is fixed in `SimpleUser`. Could check your original example with Freeswitch in the gist?

If you are not using `SimpleUser`, please look at how I fixed it in `SimpleUser` and patch your code.

Thanks.

**Comment by m-heinemann** [comment] 2020-08-14 16:03
@john-e-riordan 
I am not using `SimpleUser`, so I patched my code the same way you did in the pull request, but although the `a=inactive` is not there anymore, the hold functionality is still not working.  In fact it is now not working at all and the sound is transmitted both ways.

I am attaching the logs I get when I try to place the call on hold:
https://gist.github.com/m-heinemann/f5acead587783baa096eb64d18aa4444

**Comment by john-e-riordan** [comment] 2020-08-18 20:33
I don't see anything wrong int he gist. The offer in the INVITE from sip.js has `a=sendonly` and the answer in the 200 Ok from Freeswitch has `a=recvonly`. I would expect that the sip.js side could be sending media if it was coded up to do so. I would expect Freeswitch to be sending nothing.

**Comment by m-heinemann** [comment] 2020-08-19 17:20
I looked into this more and I think the issue is related to this: https://groups.google.com/g/discuss-webrtc/c/gsw3OEAwNKo
You can specifically see this reply from Taylor Brandstetter:
```
It does seem to be a Firefox bug. In summary, what's happening is:

1. Firefox offers "actpass"
2. Chrome answers "active". This establishes Chrome as the DTLS client, and Firefox as the DTLS server.
3. Chrome re-offers, with "actpass" (because that's what the spec says, or at least how we interpreted it for a long time)
4. Firefox offers with "active", but with the same DTLS fingerprint. Chrome doesn't like this; it's interpreted as an attempt to change

 the DTLS role from "server" to "client" without creating a new association.
To work around this, you could:

1. Detect when this occurs and change the DTLS role from "active" to "passive" before passing the SDP into setRemoteDescription. 
2. Ensure that the offer/answer direction remains consistent. Meaning, if Firefox generates the initial offer, it generates all subsequent offers as well. I'm not sure how common this practice is, but it probably would avoid a lot of interop bugs.
```
If you look at the gist you will see that although the  offer in the INVITE has `a=setup:actpass`, the answer in the 200 OK has `a=setup:active`

Do you think this is something you can solve from your end?

**Comment by john-e-riordan** [comment] 2020-08-19 18:35
Going to first try to get the issue reproduced. And then yes, as outlined, it does seem like something that could be addressed in the session description handler as a work around.

**Comment by m-heinemann** [comment] 2020-09-01 13:45
@john-e-riordan Were you able to reproduce the issue?

**Comment by john-e-riordan** [comment] 2021-01-26 16:03
I believe #898 fixes this issue. Sorry for the delay.

**Comment by eternal365** [comment] 2021-03-12 16:53
@john-e-riordan I tested hold in Chrome 88.0.4324.190 - works fine, in Firefox 84.0.2 - throws InvalidAccessError (SIP.js v0.19.0).

```
Fri Mar 12 2021 18:36:06 GMT+0200 (Eastern European Standard Time) | sip.SessionDescriptionHandler | SessionDescriptionHandler.setDescription failed - InvalidAccessError: Answer tried to set send when offer did not set recv
Fri Mar 12 2021 18:36:06 GMT+0200 (Eastern European Standard Time) | sip.Inviter | Session.setAnswer: SDH setDescription rejected...
Fri Mar 12 2021 18:36:06 GMT+0200 (Eastern European Standard Time) | sip.Inviter | Answer tried to set send when offer did not set recv
Fri Mar 12 2021 18:36:06 GMT+0200 (Eastern European Standard Time) | sip.Inviter | Failed to handle answer in 2xx response to re-INVITE
Fri Mar 12 2021 18:36:06 GMT+0200 (Eastern European Standard Time) | sip.Inviter | Answer tried to set send when offer did not set recv
```

Code used to put on hold:

```
session.invite({
    sessionDescriptionHandlerOptions: {
        hold: true
    }
});
```

Also tried as described in the [documentation](https://github.com/onsip/SIP.js/blob/master/docs/session-description-handler.md#how-do-i-put-a-session-on-hold) - same result.

**Comment by jhspyhard** [comment] 2021-11-30 21:46
I also get the same `InvalidAccessError: Answer tried to set send when offer did not set recv` error when attempting an .invite(...) on a live session in FF v94, using v0.20.0 of SIP.js using the same approach that eternal365 did.

**Comment by jhspyhard** [comment] 2022-03-30 14:07
It's a bit hacky, but I found a solution that at least seems to allow the hold functionality to work inside of Firefox as-is with SIP.js v0.20.0. Putting it out there with the hope that maybe it helps someone else as well.
```
sip.userAgent = new SIP.UserAgent({ ... });
/*
 * The following section is a workaround for an issue with placing a call on hold, when using the Firefox browser.
 * For whatever reason, when a SIP invite to place a call on hold is sent by Firefox, it includes an extra session
 * attribute asking for the asterisk to be both a=sendrecv, and a=sendonly. This confuses the asterisk and results
 * in the SIP call being dropped. However, this does NOT apply to unholding of the call.
 *
 * The following conditions must be true in order for the replacement to occur:
 *       - The originating browser must be mozilla based / Firefox.
 *       - The SIP message must be an INVITE
 *       - The SIP message must be an INVITE with a sequence number of >2. The first two sequence numbers are used
 *           during setup of the initial call.
 *       - The SIP message must include the a=sendonly attribute to indicate that this IS a hold request.
 * If any of these conditions aren't met, we simply forward the SIP message as-is.
 *
 * For more information on the bug, see https://github.com/onsip/SIP.js/issues/840
 */
var transport = sip.userAgent._transport;
transport.origSend = transport.send;
transport.send = function (s) {
    if(s.search('o=mozilla') > -1 && s.search('CSeq: \\d+ INVITE') > -1 && s.search('CSeq: [^1-2] INVITE') > -1 && s.search('a=sendonly\r\n') > -1){
        return transport.origSend(s.replace(/a=sendrecv\r\n/g, ''));
    }
    return transport.origSend(s);
};
```

**Comment by john-e-riordan** [comment] 2022-09-30 21:59
Been a while...

I failed to reproduce today with Chrome 105 putting Firefox 105 putting each other on hold in all permutations.

Is this still an issue? If so how can I reproduce?

Thanks

**Comment by chrisxdef** [comment] 2022-10-13 16:29
I am currently experiencing the same issues as stated above. I am not using simple user, but Iam implementing my own setHold function following the one in simpleUser. 

The weird part is that it totally works as expected on Google Chrome. However when I try firefox I do not get the hold music on the other parties end.

I am holding the call from web browser side, and my other device is a mobile phone. 

Let me know what I can do for you to help us both figure this out.

**Comment by jhspyhard** [comment] 2022-10-13 17:47
Earlier this week I did try integrating SIPjs v0.20.1 into my code base and pull out my workaround to see if it made a difference, however the `a=readonly` and `a=sendrecv` bug still did manifest for me when using Firefox. I haven't had time yet to pull a working example out though. I will try and find some time to make a working example here in the next week or so if someone else doesn't do it first.

**Comment by john-e-riordan** [comment] 2022-10-21 19:29
Hi. So...

I can see the behavior you are describing and understand the effect the hack which @jhspyhard has put together is having. But there is no bug with regard to what Firefox is doing (SIP.js is irrelevant as it is just passing the offers/answers along). The explanation for what you are seeing is that the system on the remote end is sending an invalid answer to the offer Firefox is making it. The hack is providing a work around for that issue by stripping out the default value of `a=sendrecv` in the session section of the SDP offer which Firefox is making. (It's worth noting that Chrome does not put a default value in the session section of the SDP so that's why the remote end does not have an issue working with Chrome).

Specifically the error you are seeing when Firefox attempts to set answer from the remote end, `InvalidAccessError: Answer tried to set send when offer did not set recv`, is Firefox complaining that the remote end sent an invalid answer in the 200 Ok with either `a=sendrecv` or `a=sendonly` in response to it's offer of `a=sendonly` in the media section of the SDP.

**Testing**

My test setup is Firefox 105.0.1 using the Demo: Audio Call - Outbound from here: https://github.com/onsip/SIP.js/blob/main/demo/README.md.
- Connect
- Place Call
- Check Hold

Placing the call the initial INVITE (CSeq 1) has an offer that looks like the below with `a=sendrecv` in both the session section (the first one) and the media section (the second one after the line starting `a=audio`). This is all valid. The values in the session section are used if there is no value specified in media section. (Again worth noting that Chrome is not currently using default values in the session section and so the issue with the remote end is not getting surfaced.)

From the RFC....
```
   A session description consists of a session-level description
   (details that apply to the whole session and all media streams) and
   optionally several media-level descriptions (details that apply onto
   to a single media stream).

   An announcement consists of a session-level section followed by zero
   or more media-level sections.  The session-level part starts with a
   `v=' line and continues to the first media-level section.  The media
   description starts with an `m=' line and continues to the next media
   description or end of the whole session description.  In general,
   session-level values are the default for all media unless overridden
   by an equivalent media-level value.
```

Here is the offer...

```
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 3831183992432470839 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 AC:AA:9C:E8:AE:73:CF:83:CB:6C:73:59:76:84:DE:1A:F1:52:4A:A6:20:4A:D1:6F:A1:A4:DD:4F:F8:34:4C:78
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 49423 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 REDACTED
a=candidate:0 1 UDP 2122187007 REDACTED 49423 typ host
a=candidate:2 1 UDP 2122252543 REDACTED 54657 typ host
a=candidate:4 1 TCP 2105458943 REDACTED 9 typ host tcptype active
a=candidate:5 1 TCP 2105524479 REDACTED 9 typ host tcptype active
a=candidate:0 2 UDP 2122187006 REDACTED 52849 typ host
a=candidate:2 2 UDP 2122252542 REDACTED 60361 typ host
a=candidate:4 2 TCP 2105458942 REDACTED 9 typ host tcptype active
a=candidate:5 2 TCP 2105524478 REDACTED 9 typ host tcptype active
a=candidate:1 1 UDP 1685987327 REDACTED49423 typ srflx raddr 192.168.1.211 rport 49423
a=candidate:1 2 UDP 1685987326 REDACTED 52849 typ srflx raddr 192.168.1.211 rport 52849
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:3828b0aef3600a9ec4284d5260555853
a=ice-ufrag:8320192c
a=mid:0
a=msid:{232add0c-8dfc-4801-b866-552f817e25b2} {0623764b-d937-4484-8347-8299a3a35054}
a=rtcp:52849 IN IP4 96.250.4.155
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:4202926363 cname:{22738195-e276-463b-947b-32212aa9d50b}
```

Then checking Hold, an in-dialog INVITE (CSeq 2) is sent with an offer to put the call on hold that looks like following with `a=sendrecv` in the session section and `a=sendonly` in the media section. All valid and the remote end should be ok with this (and use the `a=sendonly` in the media section per the standard). The @jhspyhard hack is stripping the `a=sendrecv` from the session section. There should not be any reason to need to do this other than needing to work around an issue with the remote end.

```
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 3831183992432470839 1 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 AC:AA:9C:E8:AE:73:CF:83:CB:6C:73:59:76:84:DE:1A:F1:52:4A:A6:20:4A:D1:6F:A1:A4:DD:4F:F8:34:4C:78
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 49423 UDP/TLS/RTP/SAVPF 9 101 109 0 8
c=IN IP4 REDACTED
a=candidate:0 1 UDP 2122187007 REDACTED 49423 typ host
a=candidate:2 1 UDP 2122252543 REDACTED typ host
a=candidate:4 1 TCP 2105458943 REDACTED 9 typ host tcptype active
a=candidate:5 1 TCP 2105524479 REDACTED 9 typ host tcptype active
a=candidate:1 1 UDP 1685987327 REDACTED 49423 typ srflx raddr 192.168.1.211 rport 49423
a=sendonly
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:101 0-15
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=ice-pwd:3828b0aef3600a9ec4284d5260555853
a=ice-ufrag:8320192c
a=mid:0
a=msid:{232add0c-8dfc-4801-b866-552f817e25b2} {0623764b-d937-4484-8347-8299a3a35054}
a=rtcp-mux
a=rtpmap:9 G722/8000/1
a=rtpmap:101 telephone-event/8000
a=rtpmap:109 opus/48000/2
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=setup:actpass
a=ssrc:4202926363 cname:{22738195-e276-463b-947b-32212aa9d50b}
```

That all works fine. Firefox is talking to FreeSwitch on the remote end and which responds with an answer in the 200 Ok including a `a=recvonly`.

```
v=0
o=F 1666354697 1666354699 IN IP4 REDACTED
s=F
c=IN IP6 2620:104:2031::2049
t=0 0
m=audio 50520 UDP/TLS/RTP/SAVPF 9 101
a=silenceSupp:off - - - -
a=mid:0
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=recvonly
a=rtcp:50520
a=rtcp-mux
a=setup:active
a=fingerprint:sha-256 B4:B9:90:AF:BB:C5:3B:07:32:68:B0:DB:15:55:50:12:52:3D:BA:94:B2:ED:C2:E3:53:71:04:35:36:BF:C9:AE
a=ptime:20
a=ice-ufrag:wHlHphNQ
a=ice-pwd:nuKX1SgwM1a2eA0qodeZlNxojI
a=candidate:pnbM7IOexZteE44F 1 UDP 2130706175 2620:104:2031::2049 50520 typ host
```

If you test it yourself, you will find that the broken remote end you are working with sends `a=sendrecv` (or possibly `a=sendonly`) in this 200 Ok which is invalid. Please give it try.

If you want to keep using your hack instead of fixing the remote end, I would suggest trying to use a `SessionDescriptionHandlerModifier` which can do the same striping for you. For example, you could pass it in via `SessionInviteOptions` and it will be given the entire SDP to work with. The upside is that your hack will be using supported methods and not mucking with the internals of the transport.

**Comment by john-e-riordan** [comment] 2022-11-21 16:02
Assuming issue has been laid to rest.

**Closed by john-e-riordan** 2022-11-21 16:02 UTC
Labels: Session Description Handler

**Comment by chrisxdef** [comment] 2023-01-25 20:12
@john-e-riordan Thak you for the elaboration, and I really appreciate the infestation. I will have the remote server adjusted.
