### ISSUE TITLE
RTCP-XR QoS Reports

### ISSUE THREAD

**Issue by vlameiras** [onsip/SIP.js#540] opened 2018-03-26 11:22 UTC
Hi,

I'm trying to generate QoS reports (via HOMER) of calls going through FreeSWITCH. However when I capture SIP traffic (with CaptAgent or Heplify), the RTCP-XR reports aren't there.
Does SIP.js supports any of these methods?

RTCP-XR SIP Publish
X-RTP-STAT SIP BYE/200OK

Thanks

**Comment by egreenmachine** [comment] 2018-03-27 13:00
This looks like a duplicate of #433. 

`RTCP-XR SIP Publish` looks like [`RFC6035`](https://tools.ietf.org/html/rfc6035#section-3.2). That section also specifically states that `PUBLISH` method **SHOULD NOT** be used. If we were going to tackle this, my approach would be to support the entire RFC. 

`X-RTP-STAT` header is just a header. You can manually add headers yourself as an [`extraHeader`](https://sipjs.com/api/0.9.0/session/#byeoptions). 

I don't see myself getting to this in the near future, as it is not a priority for us at the moment. We would be happy to take a PR for it though.

**Closed** 2020-08-20 20:33 UTC
Labels: duplicate, enhancement
