### ISSUE TITLE
how to set only one codec to ulaw?

### ISSUE THREAD

**Issue by Dewilas** [onsip/SIP.js#683] opened 2019-04-25 14:51 UTC
Hi, I need to set only one codec to ulaw? How to do that? Please share a simple code snippet. thank you

**Comment by egreenmachine** [comment] 2019-04-25 14:56
This is not a bug so I will be closing it. In the future please our [Google Group](https://groups.google.com/forum/#!forum/sip_js) for questions like this.

You can achieve what you want to do with [modifiers](https://sipjs.com/api/0.13.0/sessionDescriptionHandler/#modifiers-2). You can use the [stripRtpPayload](https://github.com/onsip/SIP.js/blob/master/src/Web/Modifiers.ts#L97) modifier to strip all other rtp payloads. Alternatively you can write your own modifier that does the opposite, strip everything besides what is on a whitelist.

**Closed by egreenmachine** 2019-04-25 14:56 UTC
Labels: Session Description Handler, question
