### ISSUE TITLE
clarify documentation: new SIP.UA calls start()

### ISSUE THREAD

**Issue by hansifer** [onsip/SIP.js#650] opened 2019-02-17 19:59 UTC
**Describe the bug**
Instantiating a SIP.UA seems to implicitly call .start(), but there is no mention of this in the documentation.

**Comment by james-criscuolo** [comment] 2019-02-17 20:18
Closing, duplicate of https://github.com/onsip/sipjs.com/issues/33

**Closed by james-criscuolo** 2019-02-17 20:18 UTC
