### ISSUE TITLE
Prioritize webrtc packages with dscp

### ISSUE THREAD

**Issue by thomaschaaf** [onsip/SIP.js#298] opened 2016-03-14 20:12 UTC
There is a newer method called: googDscp which can be enabled. It is used by twilio: (search for dscp)  http://media.twiliocdn.com/sdk/js/client/releases/1.3.5/twilio.js

Maybe this should be enabled for sip.js aswell?

**Comment by wakamoleguy** [comment] 2016-03-14 20:26
This is configurable by the application when creating a new outbound Session.  There's an existing bug for handling RTCConstraints on inbound InviteServerContexts (#228).  I feel strongly that we should not hardcode this, instead fixing the RTCConstraints option on `session.accept()`.

I'll close this as a duplicate of #228, as fixing that Issue would make this possible.  The additional use case for it should also pressure that Issue to get more attention.

**Closed by wakamoleguy** 2016-03-14 20:26 UTC
Labels: bug, duplicate, enhancement
