### ISSUE TITLE
Suggestion -  Error event when SIP Server is down

### ISSUE THREAD

**Issue by brunogsa** [onsip/SIP.js#216] opened 2015-08-26 14:20 UTC
Hey there!

We're trying to do something like a recovering system, which must be triggered when our SIP Server is down.

Currently, when we try to start() our User Agent, the last event being triggered is the "connecting". SIP debug messages, however, already shows that we have an error "ECONNREFUSED", since our SIP Server is down, so we were expecting an error event to be triggered - maybe the "disconnected" event.

What happens when SIP Server is up and running:

![sipjs-ok-scenario](https://cloud.githubusercontent.com/assets/4551005/9495708/49339992-4be3-11e5-8659-92d7126fe5c4.png)

![sipjs-ok-scenario-2](https://cloud.githubusercontent.com/assets/4551005/9495709/493b0678-4be3-11e5-944c-409d27efb7b3.png)

What happens when SIP Server is down:

![sipjs-connecting-1](https://cloud.githubusercontent.com/assets/4551005/9495751/7bce942e-4be3-11e5-9e99-76a411042625.png)

![sipjs-connecting-2](https://cloud.githubusercontent.com/assets/4551005/9495752/7bd81922-4be3-11e5-8631-6a57eacdd937.png)

Our code:

```
        // SIP Event Handlers
        sipUA.on('connecting', onConnecting);
        sipUA.on('connected', onConnected);
        sipUA.on('disconnected', onDisconnected);
        sipUA.on('registered', onRegistered);
        sipUA.on('unregistered', onUnregistered);
        sipUA.on('registrationFailed', onRegistrationFailed);
        sipUA.on('invite', onInvite);
        sipUA.on('message', onMessage);

        Logger.debug('[createSipUA] Added SIP event listeners to UA');

(...)

    function onConnecting(args) {
        Logger.debug('SIP UA connecting..');
    }

    function onConnected() {
        Logger.debug('SIP UA connected');
        registerSipUA();
    }

    function onDisconnected() {
        Logger.fatal('SIP UA disconnected');
    }

    function onRegistered() {
        Logger.info('SIP UA is probably registered now');
    }

    function onUnregistered(cause) {
        Logger.warn('SIP UA was unregistered:\n\t' + cause);
    }

    function onRegistrationFailed(cause) {
        Logger.fatal('SIP UA registration failed:\n\t' + cause);
    }
```

**Comment by matthieusieben** [comment] 2015-08-31 10:27
Maybe related to #217 ?

**Comment by wakamoleguy** [comment] 2015-10-16 18:53
Hrm.  I would have expected that to have some sort of error event propagate up.  I know this ticket is a little stale at this point (sorry!).  Is the issue still happening?  I'll see if I can't reproduce it.

**Comment by brunogsa** [comment] 2015-11-03 19:41
Yeah, it's still happening!
For now I'm using the working around proposed on #217!

**Comment by JimGreenberg** [comment] 2018-06-25 15:11
Related to this: the 0.11.0 release contains a major refactor to the transport code. Included in these changes is a `transportError` event that is emitted by the `Transport`. I'm going to close this for now, but if the behavior of the event isn't quite what you'd expected I think it'd be appropriate to just open a new discussion (seeing as this one is a few years old) or even a PR.

**Closed by JimGreenberg** 2018-06-25 15:11 UTC
Labels: bug
