### ISSUE TITLE
sdp: Failed to push down transport description

### ISSUE THREAD

**Issue by gnikolaev** [onsip/SIP.js#377] opened 2017-01-21 14:01 UTC
Recently discovered that with latest version of Chrome, there seems to be a problem when using session.hold(). I get the following error in the browser when executing it:

sip-0.7.3.min.js:36 DOMException: Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.
c.print @ sip-0.7.3.min.js:36
c.(anonymous function) @ sip-0.7.3.min.js:36
b.(anonymous function) @ sip-0.7.3.min.js:36
(anonymous) @ sip-0.7.3.min.js:42

I am using sipjs 0.7.3 and Google Chrome Version 55.0.2883.95 (64-bit). 
This is happening on either mac or Windows.

I have tested it with sipjs 0.7.6 and the issue is still present.

**Comment by joshelson** [comment] 2017-01-24 01:41
Is this a call TO the browser @gnikolaev? If so, the error there is pretty straightforward. 

Chrome is expecting DTLS setup attribute in the SDP of: setup:actpass. If you're sending something else, it's going to fail.

Can you send the SIP INVITE sequence? Will likely be pretty straightforward from there, but this probably isn't an issue with sip.js.

**Comment by gnikolaev** [comment] 2017-01-24 08:23
Thanks for coming back @joshelson  
This is actually an outgoing call where we get the error, so the browser is originating the call. The actual call is established successfully with both ways audio working perfectly fine. 
Tested on incoming calls TO the browser and the hold is actually working in that scenario. Its only when doing outbound.

Here are the logs from both the FreeSWITCH and the Chrome Console which include the whole communication including the SIP trace:
FS -> http://pastebin.com/3HskKf0g
Chrome -> http://pastebin.com/gXxWq25Q

Thank you in advance.

**Comment by james-criscuolo** [comment] 2017-01-24 15:38
Lines 216 and 263 of your Freeswitch pastebin show Freeswitch replying with `setup = active`. The error is a little misleading in that it says "offerer," but I do believe this problem rests solely with Freeswitch. If this is indeed something that  can not be tweaked in Freeswitch's configuration, it would qualify for a hack.

**Comment by gnikolaev** [comment] 2017-01-24 21:59
@james-criscuolo Thanks for reviewing the logs. 
I am guessing you are talking about the Chrome log and not the Freeswitch Log. 
I can certainly see your point there, however, if my understanding of the RFC5763 is correct, setup must be set to "actpass" only on the "offer" i.e. from the inviting side. For the answer, setup should be set either as "active" or "passive". 

Also very interesting is the fact that when trying this same exact setup but using Firefox instead of Google Chrome, hold/unhold is working perfectly fine. 

Here are the longs from such call:
Firefox: http://pastebin.com/Hg3YX7sJ
FreeSWITCH when using FF: http://pastebin.com/ZPZq639d

**Comment by gnikolaev** [comment] 2017-01-25 14:10
@james-criscuolo @joshelson just further to my previous messages, I have noticed that depending on the direction of the call, the SDP setup sipjs sends out is different.
When the call is incoming, on session.hold() from the receiving party we have setup=actpass in the SDP. 
When its an outgoing call, on session.hold() from the origination party we have setup=active in the SDP.

Now I am not very familiar if these messages are based on what it has been received from the other party but its a bit confusing why its behaving differently. 

I also noticed a different behaviour between Chrome and Firefox. Both making outbound calls, on session.hold():
Firefox: setup=passive
Chrome: setup=active

Thanks

**Comment by james-criscuolo** [comment] 2017-01-25 14:30
In the end, whatever change is made here will end up being in the hacks.js file as a browser hack (or hacks, if there are multiple issues). The sdp is generated by calls down into browser objects (RTCPeerConnection), so SIP.js does not do much (outside of hacks) in terms of altering this information. There are options that can be passed to the RTCPeerConnection constructor, so maybe these will cover it, but if not, hacks will be necessary.

In terms of what the options or hacks should alter, in both situations being discussed we want to do whatever the spec highlights as the right answer.

**Comment by gnikolaev** [comment] 2017-01-25 15:24
@james-criscuolo without trying to be smart or arrogant but what does it means that it needs to go into hacks.js? I mean I understand what a hack is and I understand what needs to happen (more or less) but if this is the only option, what is the procedure of getting it there? Also, if this is certainly a Chrome bug, I am happy to report it to them so they can fix it. 

My point with my previous message was, is this something that sipjs treats differently based on the browser, or it is controlled by the other side (in this case Freeswitch).
From what I can see, when using Firefox, sipjs sends actpass, FS responds with active, then on session.hold, sipjs sends out passive. 

When using Chrome, sipjs sends actpass, FS responds with active, then on session.hold sipjs sends out active.

**Comment by james-criscuolo** [comment] 2017-01-25 16:01
In the above, when you say "sip.js sends actpass," sip.js does not control that, or do anything specific to cause that to happen. We use built-in browser APIs to generate the SDP, so it's differences in the browser implementations that cause your problem.

Saying it needs to go into hacks.js just means it goes with the rest of our hacks.

**Comment by gnikolaev** [comment] 2017-01-25 21:17
@james-criscuolo Interesting enough, I have just tried the same browser, the same Freeswitch server, different js library (I tried with sipml5) and Hold is working perfectly fine. Is there any chance the wrong API calls are made when executing the session.hold? I am not a developer myself so I don't know how to fix that in the code but I am just voiding out the elements one by one and it seems to be something within sipjs. 

Here is the log from a call made with sipml5 just for a reference: http://pastebin.com/bfHQ9TdL

**Comment by james-criscuolo** [comment] 2017-01-27 14:27
It looks like SIPml5 has their own SDP stack, so they do not rely on the browsers to make the SDP.

The issue here is clearly with the SDP generated by the browsers, and SIP.js can do something about it, in the form of a hack on the generated SDP or extra option sent to the browser during SDP generation. I'm not trying to say SIP.js is not at fault, I'm just saying the problem is not directly in our code. That does not mean our code can not provide the solution.

**Comment by gnikolaev** [comment] 2017-01-27 21:58
@james-criscuolo Thanks a lot for coming back. I totally understand and agree. Just want to clarify that I am not looking for the guilty one and hope it did not come across that way. This is an open source project so I understand the risk and the benefits of using such.

So what are the options/possibilities of having this "hack"? Also since this is certainly a problem on the Chrome site, I would open a bug with them so they can consider it. 

Let me know if there is anything I can help to speed up the process of getting the hack.

**Comment by gnikolaev** [comment] 2017-01-27 22:03
Actually, as i have opened a talk on discuss-webrtc group, here is the response I got and in it we have open a bug for that. https://groups.google.com/forum/#!msg/discuss-webrtc/fMxxqCRRihE/-k6OISsaGQAJ;context-place=forum/discuss-webrtc

**Comment by egreenmachine** [comment] 2017-06-01 15:32
This looks like a bug with WebRTC and not SIP.js. I am going to close this issue, if it turns out we are at fault here please re-open. Thanks.

**Closed by egreenmachine** 2017-06-01 15:32 UTC
