### ISSUE TITLE
while making call, Sipjs directly goto loudSpeaker..

### ISSUE THREAD

**Issue by harishk663** [onsip/SIP.js#138] opened 2014-12-22 16:07 UTC
hai all,
     I am doing the project in sip js.I just converted my sip js into apk using crosswalk tools https://crosswalk-project.org/documentation/cordova/develop_an_application.html .Once i create into apk, i just make call from phone to tablet.while making a call,my media functionality directly hit to loud speaker(main speaker).

My question is once i make a call, my media functionality directly go ear speaker(secondary speaker),if you have any idea about this issue please share your knowledge,,

**Comment by Destreyf** [comment] 2015-01-01 12:25
@harishk663 

I am currently working on a SIP.js project on android as well, i am using cordova specifically at the moment, and the issue is that web pages and apps are treated as Media, like music instead of calls.

You can use this tool: https://github.com/alongubkin/audiotoggle to force the audio out the ear piece.

**Comment by harishk663** [comment] 2015-01-03 05:35
@Destreyf 

I am also currently working in sip.js project on android.i have converted my sip js into .apk using crosswalk cordova application https://crosswalk-project.org/documentation/cordova.html once i converted into apk my audio and video functionality in not working.If i add plugin https://github.com/alongubkin/audiotoggle also my audio and video functionality is not working.

**Comment by svarunan** [comment] 2016-06-21 00:46
@harishk663 I think you created a Hybrid android app. It does not a native app to have full control over medial playback devices. Its not a SIPjs issue that i know. Its a HTML5 limitation. Your issue could be same like [this](http://stackoverflow.com/questions/37589959/webrtc-control-audio-playback-on-android-mobile-device-chrome-broswer)

**Comment by LaurieScheepers** [comment] 2017-04-07 11:14
I am also trying to get the audio to go through to the earpiece. Anyone here has a solution?

**Comment by egreenmachine** [comment] 2017-10-09 15:27
We believe that this issue may be resolved in the latest tagged version [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). Can you please retest with that version and let us know if this is still an issue. We will close this issue on 11/1/17 if we do not hear back. Thanks.

**Comment by egreenmachine** [comment] 2017-11-01 15:32
As stated in previous post, closing due to inactivity and proposed solution in 0.8.X. If this turns out to still be an issue, please re-open.

**Closed by egreenmachine** 2017-11-01 15:32 UTC
Labels: interop
