### ISSUE TITLE
Does not work in Safari with linphone-sdk

### ISSUE THREAD

**Issue by serrg1994** [onsip/SIP.js#813] opened 2020-05-14 10:09 UTC
When make a call to linphone from Safari I see only local videos. For Google Chrome it works fine.

**Comment by egreenmachine** [comment] 2020-05-14 10:12
**Describe the bug**
A clear and concise description of what the bug is.

**Logs**
Please include a [gist](https://gist.github.com/) or attached file with full logs. If this is not included, the first response will likely be requesting them.

**To Reproduce (if possible)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Observed behavior**
A clear and concise description of what actually happened

**Environment Information**
 - Backend Server and version
 - Browser and version

**Additional context**
Add any other context about the problem here.

Closing due to lack of information. See our bug template which I have included on this post. Feel free to reopen if you can provide more information.

**Closed by egreenmachine** 2020-05-14 10:12 UTC
