### ISSUE TITLE
Early media causes problem if 200 comes fast

### ISSUE THREAD

**Issue by matthieusieben** [onsip/SIP.js#242] opened 2015-10-23 14:40 UTC
During an outgoing session, when a 200 answer comes immediately after a 183, there is a race condition which causes the following error:

```
Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS
```

What happens is that `session.status` is set to `C.STATUS_EARLY_MEDIA` in after the `setDescription` promise is resolved ([here](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L1555)). If the 200 response is processed before that callback is triggered, then [this check](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L2091) will fails and `setDescription` will be called again.

I believe the correct solution here is to set the status to `C.STATUS_EARLY_MEDIA`, and muting local streams, [before](https://github.com/onsip/SIP.js/blob/1245245051b86be7e908d4913d149d35abf437c7/src/Session.js#L1918) invoking `setDescription()`

**Comment by matthieusieben** [comment] 2015-10-23 14:41
My current workaround is to set the `session.status` to `C.STATUS_EARLY_MEDIA` before the `setDescription` method is called.

**Comment by zxcpoiu** [comment] 2016-01-22 07:22
Same issue encountered

**Comment by egreenmachine** [comment] 2017-10-09 15:24
We believe that this issue may be resolved in the latest tagged version [0.8.0](https://github.com/onsip/SIP.js/releases/tag/0.8.0). Can you please retest with that version and let us know if this is still an issue. We will close this issue on 11/1/17 if we do not hear back. Thanks.

**Comment by matthieusieben** [comment] 2017-10-12 11:53
Sadly, I no longer work for the same company and will not be able to check.

You should however be able to simulate the behaviour described here by reasoning on your new code. Note that simply refactoring may not have been enough to fix this issue.

**Comment by egreenmachine** [comment] 2017-10-12 12:04
It was not simply a refactor, but the entire media code was re-written. I believe that this race condition is no longer possible. I am going to close this, if someone else is experiencing this they can re-open it.

**Closed by egreenmachine** 2017-10-12 12:04 UTC

**Comment by AlekseyKost** [comment] 2020-01-28 10:52
In our project we have two types of phone numbers:
- the number using early media on 183 "progress" with custom tone music
- the number with answering machine, where 200 answer comes immediately after a 183 and where we are getting an error, causes by "Bad media description"

In our service we have a handler which allows early media to work: 

```
sipSession.on('progress', (response) => {
	if (response.statusCode === 183) {
	    sipSession.sessionDescriptionHandler.setDescription(response.body).catch((exception) => {
	        sipSession.logger.warn(exception);
	        sipSession.failed(response, 'Bad Media Description');
	        sipSession.terminate({
	            statusCode: 488,
	            reason_phrase: 'Bad Media Description'
	        });
	    });
```

The problem is during an outgoing session, when a 200 answer comes immediately after a 183, we are getting error with fields in "failed" response:
statusCode: 200
reasonPhrase: "OK"

So the implemented workaround for this case is a timeout with the delay: 
 
```
sipSession.on('progress', (response) => {
    if (response.statusCode === 183) {
	    this.waitingForApplyingAnswer(sipSession, response);
    }	
...
});	

private waitingForApplyingAnswer(session, response) {
    let i = 1,
        clearTimer;
    setTimeout(function check() {
        i++;
        clearTimer = setTimeout(check, 10);
        if ( session.hasAnswer || i > 14) {
            if ( session.hasAnswer ) {
                clearTimeout(clearTimer);
            } else if ( i === 15 ) {
            	clearTimeout(clearTimer);
                session.sessionDescriptionHandler.setDescription(response.body).catch((exception) => {
                    session.logger.warn(exception);
                    session.failed(response, 'Bad Media Description');
                    session.terminate({
                        statusCode: 488,
                        reason_phrase: 'Bad Media Description'
                    });
                });
            }
        }
    }, 10);
}
```

Is it appropriate approach to solve this issue from SIP.JS perspective? Could it cause some problems?
Could you propose some better solution?
