### ISSUE TITLE
Failed to set local audio description streams

### ISSUE THREAD

**Issue by gnikolaev** [onsip/SIP.js#293] opened 2016-02-28 00:08 UTC
Using sip.js 0.7.3 and freeswitch 1.6.6 and when trying to establish a call between a softphone (Zoiper) and sipjs ua I get the following message in the Chrome Console: 
sip.invitecontext.mediahandler | Failed to set local answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set local audio description streams..c.print @ sip-0.7.3.min.js:36c.(anonymous function) @ sip-0.7.3.min.js:36b.(anonymous function) @ sip-0.7.3.min.js:36(anonymous function) @ sip-0.7.3.min.js:42
sip-0.7.3.min.js:36 Sun Feb 28 2016 00:01:59 GMT+0000 (GMT) | sip.transport | sending WebSocket message:

SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/WSS 195.39.198.10:7443;rport;branch=z9hG4bKNUK2F5j93D0NF
To: <sip:pb3pt490@g6qpojugmaui.invalid;transport=ws>;tag=0n00re9vlk
From: "10008" <sip:10008@iptel.bg>;tag=65Uv06av3gy3g
Call-ID: 521fdf0b-5851-1234-348a-000c29c9b13a
CSeq: 87972793 INVITE
Supported: outbound
User-Agent: SIP.js/0.5.0-devel BB
Content-Length: 0

The full GIST is available here: http://pastebin.com/KpzwxpwF
And the logs from the Freeswitch available here: http://pastebin.com/CV3HLZAY

Please help as I currently can not use the sipjs as no calls can be established.

**Comment by wakamoleguy** [comment] 2016-02-29 14:39
Hi,

> m=audio 26606 RTP/SAVPF 3 101 13
> a=rtpmap:3 GSM/8000
> a=rtpmap:101 telephone-event/8000
> a=rtpmap:13 CN/8000

It does not look like FreeSwitch is offering a codec that Chrome nor Firefox supports.  Please make sure that you are offering Opus, G.711, and/or G.722. 

In either case, this is a setup issue unique to your environment, and not a bug in SIP.js.  I am going to close this Issue, and please feel free to follow up [on the mailing list](https://groups.google.com/forum/#!forum/sip_js).

**Closed by wakamoleguy** 2016-02-29 14:39 UTC
