### ISSUE TITLE
Option to stop sending PRACKs

### ISSUE THREAD

**Issue by kirill-konshin** [onsip/SIP.js#357] opened 2016-10-05 20:28 UTC
In some systems PRACKs are not supported and lead to 4xx errors.

PRACKs are covered by a separate RFC https://www.ietf.org/rfc/rfc3262.txt and are not a part of SIP RFC 3261. This RFC is focused on guaranteed establishing of a media session before 200OK. In RingCentral system there are no scenarios, which require a media session before the call is established. Moreover, most of SIP flows are built in an way where a leg is Answered before it any media is played.

With PRACKs calls are successfully established, but users get 4xx errors so the logs are not clean.

It was suggested to use rel100 (http://sipjs.com/api/0.7.0/ua_configuration_parameters/#rel100) to control behavior, but rel100 is already UNSUPPORTED by default. What value should be used to disable PRACKs?

**Comment by egreenmachine** [comment] 2016-10-05 20:39
Can you please create a (gist)[https://gist.github.com/] with SIP.js logs? Include the top of the logs from SIP.js that prints out the config as well.

**Comment by kirill-konshin** [comment] 2016-10-05 20:47
```
configuration parameters after validation:
viaHost: "xxx.invalid"
uri: sip:xxx@xxx
wsServers: [{"ws_uri":"wss://xxx:8083","sip_uri":"<sip:xxx:8083;transport=ws;lr>","weight":0,"status":0,"scheme":"WSS"}]
password: NOT SHOWN
registerExpires: 600
register: true
registrarServer: sip:xxx
wsServerMaxReconnection: 3
wsServerReconnectionTimeout: 4
connectionRecoveryMinInterval: 2
connectionRecoveryMaxInterval: 30
keepAliveInterval: 0
extraSupported: []
usePreloadedRoute: false
userAgentString: "SIP.js/0.7.4"
iceCheckingTimeout: 5000
noAnswerTimeout: 60000
stunServers: ["stun:xxx:19302"]
turnServers: []
traceSip: true
hackViaTcp: false
hackIpInContact: false
hackWssInTransport: false
hackAllowUnregisteredOptionTags: false
contactTransport: "ws"
forceRport: false
autostart: true
rel100: "none"
replaces: "none"
mediaHandlerFactory: function defaultFactory(session, options) {
  return new MediaHandler(session, options);
}
authenticationFactory: undefined
authorizationUser: "xxx"
instanceId: "xxx"
sipjsId: "sf44o"
hostportParams: "xxx"
media: undefined
```
```
PRACK sip:xxx@xxx:5080 SIP/2.0
Route: <sip:xxx:8080;transport=ws;r2=on;lr=on;did=e11.57b>
Route: <sip:xxx:5060;r2=on;lr=on;did=e11.57b>
Via: SIP/2.0/WSS xxx.invalid;branch=xxx
Max-Forwards: 70
To: <sip:xxx@xxx>;tag=xxx
From: <sip:xxx@xxx>;tag=xxx
Call-ID: xxx
CSeq: 8993 PRACK
RAck: undefined 8992 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.5
Content-Length: 0
```
```
SIP/2.0 400 Bad Request
Via: SIP/2.0/WSS xxx.invalid;rport=41140;received=xxx;branch=xxx
From: <sip:xxx@xxx>;tag=xxx
To: <sip:xxx@xxx>;tag=xxx
Call-ID: xxx
CSeq: 8993 PRACK
Error-Info: <sip:xxx@xxx>;cause="[line 009] SIP syntax error"
Content-Length: 0
```

**Comment by egreenmachine** [comment] 2016-10-05 20:53
Can you please include the full logs with the trace sip? Feel free to censor any ip addresses, passwords etc. I need to see the SIP interaction that is happening that causes SIP.js to send a PRACK.

**Comment by egreenmachine** [comment] 2016-10-06 14:43
Based on the logs that you sent me off channel, it looks like the issue is actually with SIP.js. We are definitely sending a PRACK when we are not supposed to. Do you have any local changes to SIP.js source code? I am going to try to reproduce this locally to see why it is happening so I can get a fix pushed ASAP.

**Comment by egreenmachine** [comment] 2016-10-10 14:26
This is not happening in the vanilla build of SIP.js but is instead local to your changes. We are following up outside of this channel to get a working solution. Closing this issue.

**Closed by egreenmachine** 2016-10-10 14:26 UTC
