### ISSUE TITLE
TravisCI: sip.invitecontext.mediahandler | unable to acquire streams

### ISSUE THREAD

**Issue by kirill-konshin** [onsip/SIP.js#368] opened 2017-01-05 21:24 UTC
I have a strange error in Travis https://travis-ci.org/ringcentral/ringcentral-web-phone/builds/189322432#L206.

Test makes real call from one RingCentral account to another.

Chrome flags:
--use-fake-ui-for-media-stream
--allow-http-screen-capture
--disable-web-security
--no-sandbox
 
Works on my Mac but doesn’t work on Travis.
 
I have found a relevant GH issue https://github.com/onsip/SIP.js/issues/26.

**Comment by egreenmachine** [comment] 2017-01-05 21:40
The issue you linked is not related to Travis CI, but intermittent browser behavior. For testing SIP.js [overrides getUserMedia](https://github.com/onsip/SIP.js/blob/master/test/helpers/HTML5.js#L48) so that it will pass. It appears the tests you are running are not SIP.js tests (we do not use Karma in our tests) and I have confirmed that the SIP.js tests are working correctly. Since this appears to not be a SIP.js issue I am going to close this.

**Closed by egreenmachine** 2017-01-05 21:40 UTC

**Comment by kirill-konshin** [comment] 2017-01-05 21:44
Tests that I run heavily use SIP.JS, this is clearly an issue between SIP.JS and Travis CI Chrome, so please reopen and help to investigate.

**Comment by egreenmachine** [comment] 2017-01-05 21:46
Please try overriding getUserMedia and trying again. If the issue is present, let us know how to replicate and we will investigate.

**Comment by kirill-konshin** [comment] 2017-01-05 21:48
Can you provide more instructions what and how to override? There is only one way to reproduce - run RC Web Phone tests in Travis...

**Comment by egreenmachine** [comment] 2017-01-05 21:50
Please see our [test helper that overrides getUserMedia](https://github.com/onsip/SIP.js/blob/master/test/helpers/HTML5.js#L48). We cannot debug your application, if it is a SIP.js issue that can be reproduced outside of that we can investigate.

**Comment by kirill-konshin** [comment] 2017-01-05 22:01
I have added the override (lines 40...67), it did not help. The error is still the same:

```
ERROR: 'Thu Jan 05 2017 21:57:20 GMT+0000 (UTC) | sip.invitecontext.mediahandler | unable to acquire streams'
ERROR: NavigatorUserMediaError{constraintName: '', message: '', name: 'DevicesNotFoundError'}
```

https://travis-ci.org/ringcentral/ringcentral-web-phone/builds/189334085#L206

Error occurs when SIP.JS tries to make a call, it is not the problem of application, but probably because of lack of audio devices in Travis's Chrome.

**Comment by kirill-konshin** [comment] 2017-01-27 21:01
Any updates on this? I have provided all possible information from Travis CI.

**Comment by james-criscuolo** [comment] 2017-01-30 14:31
If you could narrow this down to an extremely small case involving SIP.js and little to no third party code, we could give this a look, otherwise it's hard to be sure that SIP.js is indeed at fault here. If SIP.js is indeed the culprit, it should be easy to show with a small example.

**Comment by kirill-konshin** [comment] 2017-01-31 19:28
Here you go:
https://travis-ci.org/ringcentral/ringcentral-web-phone/builds/197064197#L206

```
ERROR: 'Tue Jan 31 2017 19:24:57 GMT+0000 (UTC) | sip.invitecontext.mediahandler | unable to acquire streams'
ERROR: NavigatorUserMediaError{constraintName: '', message: '', name: 'DevicesNotFoundError'}
```

I assume that happens because TravisCI does not have microphone (obviously), so we need to somehow trick the SIP.JS and supply some sort of an object that mimics the real device...

Source code of the test:
https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone-bare.spec.js

Nothing except SIP.JS is used here, no RC patches.

**Comment by james-criscuolo** [comment] 2017-01-31 19:46
There is too much in this file for me to say without a doubt that SIP.js is at fault. Here are a few examples:

- [Karma](https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone-bare.spec.js#L3) is not included in SIP.js, so I can't be sure it isn't messing with anything

- [This SDK](https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone-bare.spec.js#L110) could be loading something that messes with getUserMedia.

We have [working tests involving getUserMedia](https://github.com/onsip/SIP.js/blob/master/test/spec/MediaStreamManager.js#L23). We override it in all cases, but that should be done in testing. Unless I see a script I can run myself with sip.js and no other dependecies, I have no way of fixing this.

**Comment by kirill-konshin** [comment] 2017-01-31 22:44
I can't make it smaller. It has to get credentials for SIP servers in order to work. Neither Karma nor SDK add anything to getUserMedia. And both are required for the test, Karma is a runner, SDK is used to authenticate.

The error happens on `userAgent.invite` call.

I have added polyfill that was mentioned earlier *before* the SIP.JS file and now I am getting:

```
ERROR: 'Tue Jan 31 2017 22:43:31 GMT+0000 (UTC) | sip.invitecontext.mediahandler | error adding stream'
ERROR: TypeError{}
```

**Comment by kirill-konshin** [comment] 2017-01-31 23:01
I have launched Chrome with `--use-fake-device-for-media-stream` and the `DevicesNotFoundError` error has gone, a fake `MediaStream` is created via fake `getUserMedia` (by Chrome, not by polyfill).

Unfortunately, now I get the following:

```
WARN: 'Tue Jan 31 2017 22:58:03 GMT+0000 (UTC) | sip.inviteclientcontext | Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set audio send codecs..'
```

**Comment by kirill-konshin** [comment] 2017-01-31 23:48
Bottom line:

### [Polyfill](https://github.com/onsip/SIP.js/blob/master/test/helpers/HTML5.js#L41)

```
ERROR: 'Tue Jan 31 2017 22:48:00 GMT+0000 (UTC) | sip.invitecontext.mediahandler | error adding stream'
ERROR: TypeError{}, 'TypeError: Failed to execute 'addStream' on 'RTCPeerConnection': parameter 1 is not of type 'MediaStream'.
    at TypeError (native)
    at EventEmitter.<anonymous> (http://localhost:9876/base/bower_components/sip.js/dist/sip.js?81acfd1663618b3c8f494cf83b0f2106b4c39265:11642:29)
    at Array.forEach (native)
    at EventEmitter.addStreams (http://localhost:9876/base/bower_components/sip.js/dist/sip.js?81acfd1663618b3c8f494cf83b0f2106b4c39265:11641:15)'
```

### Fake Device flag for Chrome

```
WARN: 'Tue Jan 31 2017 22:58:03 GMT+0000 (UTC) | sip.inviteclientcontext | Failed to set remote answer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set audio send codecs..'
```

**Comment by james-criscuolo** [comment] 2017-02-01 14:25
Both of these logs point to issues at the browser level. Unless you are attempting to test browser capability of generating SDP (in which case, fake devices probably won't help), I suggest faking these objects (RTCPeerConnection, for one) in your test as well.

**Comment by kirill-konshin** [comment] 2017-02-01 18:08
That's true, it's not directly related to SIP.JS, it's mostly fake browser objects that are incompatible with SIP.JS. Can you provide any information how to mock RTCPeerConnection in order to satisfy at least SIP.JS, or how to skip media at all during tests.

**Comment by james-criscuolo** [comment] 2017-02-01 18:13
We do a bit of that here: https://github.com/onsip/SIP.js/blob/master/test/spec/WebRTC.MediaHandler.js

**Comment by kirill-konshin** [comment] 2017-02-08 01:59
I think SIP.JS can benefit a lot if support of TravisCI and headless Chrome env will be added... It is a very complex task though and it has to be done by someone with good knowledge of all WebRTC-related and other low-level parts. From my end I can assist to reproduce TravisCI environment and provide credentials for testing.

**Comment by james-criscuolo** [comment] 2017-02-08 14:59
There could be use for this, however it is not our primary goal with SIP.js. It would certainly be nice to have, but it sounds like a project in and of itself (that multiple webrtc libraries would take interest in) which would also require its own maintenance. Demand for this is also low, so it's not something that I see us implementing in the near future. Out test suite is sufficient for our purposes, although I do hope to clean up the dependencies surrounding it at some point.

We would be more than happy to view PRs in this space though :)
