### ISSUE TITLE
Crusade against Utils.js

### ISSUE THREAD

**Issue by wakamoleguy** [onsip/SIP.js#160] opened 2015-03-06 21:57 UTC
I have strong, negative feelings towards the existence of **Utils.js**.  At best, it is a miscellaneous bag of functions with no strong connection between them.  At worst, it is a thorn in the side of dependency graphs everywhere.

In an ideal world, we could strip each function out of **Utils.js** and into either into smaller, semantically themed modules or re-home some functions to existing modules that use them.

This ticket is somewhat low priority, of course, as it should have no direct outward effect on the behavior of the library.

**Comment by egreenmachine** [comment] 2017-12-06 17:51
While  we would like to get rid of `Utils.js`, there is no problem with keeping it around. Due to the fact that it is not a bug, I am going to close this issue.

**Closed by egreenmachine** 2017-12-06 17:51 UTC
Labels: enhancement, inconsistency
